"""Labeled benchmark cases shared by batch_test.py (coverage) and
train_model.py (training data).

Each case: name, url, metadata (camelCase, as sent by the content script),
expected label in {legit, phish}. Used to (a) verify the deterministic pipeline
and (b) train/validate the stage-2 ML model.
"""

STEP1 = {
    'passwordFields': 1,
    'forms': 1,
    'hiddenElements': 2,
    'externalScripts': 4,
    'permissionRequests': 0,
    'promptInjectionSignals': 0,
    'hasLoginIntent': True,
    'title': 'Log in - Example Corp',
}

CASES = [
    # ------------------------------------------------------------- legit
    {'name': 'Legit article',
     'url': 'https://example.com/article',
     'metadata': {'title': 'Example Article', 'passwordFields': 0, 'forms': 0,
                  'hiddenElements': 2, 'externalScripts': 3,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': False},
     'expected': 'legit'},
    {'name': 'GitHub blog',
     'url': 'https://saadh393.github.io/blog/adapter-port-architecture-two-cases',
     'metadata': {'title': 'Adapter Port Architecture', 'passwordFields': 0,
                  'forms': 0, 'hiddenElements': 2, 'externalScripts': 6,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': False},
     'expected': 'legit'},
    {'name': 'Legit login (TSTPrep)',
     'url': 'https://tstprep.com/user-login/',
     'metadata': {'title': 'Login', 'passwordFields': 1, 'forms': 1,
                  'hiddenElements': 2, 'externalScripts': 4,
                  'permissionRequests': 0, 'promptInjectionSignals': 1,
                  'hasLoginIntent': True},
     'expected': 'legit'},
    {'name': 'Gmail inbox (noisy)',
     'url': 'https://mail.google.com/mail/u/0/#inbox',
     'metadata': {'title': 'Gmail', 'passwordFields': 0, 'forms': 1,
                  'hiddenElements': 6, 'externalScripts': 12,
                  'permissionRequests': 0, 'promptInjectionSignals': 1,
                  'hasLoginIntent': False},
     'expected': 'legit'},
    {'name': 'Gmail clean',
     'url': 'https://mail.google.com/mail/u/0/#inbox-clean',
     'metadata': {'title': 'Gmail Clean', 'passwordFields': 0, 'forms': 0,
                  'hiddenElements': 4, 'externalScripts': 8,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': False},
     'expected': 'legit'},
    {'name': 'Amazon sign-in (same-domain)',
     'url': 'https://www.amazon.com/ap/signin',
     'metadata': {'title': 'Amazon Sign-In', 'passwordFields': 1, 'forms': 1,
                  'hiddenElements': 3, 'externalScripts': 9,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True, 'formDestination':
                  'https://www.amazon.com/ap/signin'},
     'expected': 'legit'},
    {'name': 'Wikipedia',
     'url': 'https://en.wikipedia.org/wiki/Phishing',
     'metadata': {'title': 'Phishing - Wikipedia', 'passwordFields': 0,
                  'forms': 0, 'hiddenElements': 3, 'externalScripts': 2,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': False},
     'expected': 'legit'},
    {'name': 'Hard negative: Stripe checkout',
     'url': 'https://checkout.stripe.com/c/pay/cs_test_x',
     'metadata': {'title': 'Secure checkout - 42.00 USD', 'passwordFields': 0,
                  'forms': 1, 'hiddenElements': 16, 'externalScripts': 18,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': False, 'brandHints': 'Stripe checkout'},
     'expected': 'legit'},
    {'name': 'Hard negative: OAuth page',
     'url': 'https://accounts.google.com/o/oauth2/v2/auth',
     'metadata': {'title': 'Sign in - Google Accounts', 'passwordFields': 1,
                  'forms': 1, 'hiddenElements': 5, 'externalScripts': 15,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True},
     'expected': 'legit'},
    {'name': 'Hard negative: payment (PayPal checkout)',
     'url': 'https://www.paypal.com/webapps/hermes?flow=1-PSA&country.x=US',
     'metadata': {'title': 'Checkout | PayPal', 'passwordFields': 0,
                  'forms': 2, 'hiddenElements': 9, 'externalScripts': 20,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': False},
     'expected': 'legit'},
    {'name': 'Hard negative: university login (IIT Jammu)',
     'url': 'https://saral.iitjammu.ac.in/login',
     'metadata': {'title': 'Sign in - IIT Jammu SARAL', 'passwordFields': 1,
                  'forms': 1, 'hiddenElements': 2, 'externalScripts': 5,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True},
     'expected': 'legit'},
    {'name': 'Hard negative: university login (MIT CAS)',
     'url': 'https://my.mit.edu/cas/login',
     'metadata': {'title': 'Sign in to Your Account', 'passwordFields': 1,
                  'forms': 1, 'hiddenElements': 3, 'externalScripts': 4,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True},
     'expected': 'legit'},
    # --------------------------------------------------------- phish
    {'name': 'Phish: synthetic domain',
     'url': 'https://phish.example/fake-bank',
     'metadata': {'title': 'Bank Login', 'passwordFields': 2, 'forms': 1,
                  'hiddenElements': 8, 'externalScripts': 15,
                  'permissionRequests': 0, 'promptInjectionSignals': 2,
                  'hasLoginIntent': True},
     'expected': 'phish'},
    {'name': 'Phish: brand impersonation login',
     'url': 'https://paypal-account-secure-check.com/login',
     'metadata': {'title': 'PayPal - Log in to your account',
                  'passwordFields': 1, 'forms': 1, 'hiddenElements': 2,
                  'externalScripts': 6, 'permissionRequests': 0,
                  'promptInjectionSignals': 0, 'hasLoginIntent': True,
                  'brandHints': 'PayPal'},
     'expected': 'phish'},
    {'name': 'Phish: credential exfiltration',
     'url': 'https://weblogin.example.com/account',
     'metadata': {'title': 'Log in', 'passwordFields': 1, 'forms': 1,
                  'hiddenElements': 3, 'externalScripts': 5,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True,
'formDestination': 'https://collect-harvest.example.net/l',
                   'formActionDomainMismatch': True,
                   'credentialSubmissionDestinationMismatch': True},
     'expected': 'phish'},
    {'name': 'Phish: punycode Google',
     'url': 'https://xn--ggle-0nda.com/accounts/login',
     'metadata': {'title': 'Google accounts - Sign in', 'passwordFields': 1,
                  'forms': 1, 'hiddenElements': 1, 'externalScripts': 3,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True, 'brandHints': 'Google'},
     'expected': 'phish'},
    {'name': 'Phish: OTP hidden login',
     'url': 'https://secure-verify-login-app.com/two-factor',
     'metadata': {'title': 'Security check - verify your identity',
                  'passwordFields': 1, 'forms': 1, 'hiddenElements': 1,
                  'externalScripts': 4, 'permissionRequests': 1,
                  'promptInjectionSignals': 1, 'hasLoginIntent': True,
                  'otpRequest': True},
     'expected': 'phish'},
    {'name': 'Phish: Apple ID lookalike',
     'url': 'https://apple-id-verify.tk/account/login',
     'metadata': {'title': 'Apple ID - Sign In', 'passwordFields': 1,
                  'forms': 1, 'hiddenElements': 1, 'externalScripts': 2,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True, 'brandHints': 'Apple ID'},
     'expected': 'phish'},
    {'name': 'Phish: Facebook lookalike',
     'url': 'https://facebook-secure-login.co.uk/f/login',
     'metadata': {'title': 'Facebook - Log in', 'passwordFields': 1,
                  'forms': 1, 'hiddenElements': 1, 'externalScripts': 6,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True, 'brandHints': 'Facebook'},
     'expected': 'phish'},
]

# Tiny validation split (unseen domains/brands) for generalization checks.
VALIDATION_CASES = [
    {'name': 'Legit (unseen SaaS)',
     'url': 'https://app.asana.com/login',
     'metadata': {'title': 'Log in - Asana', 'passwordFields': 1, 'forms': 1,
                  'hiddenElements': 2, 'externalScripts': 7,
                  'permissionRequests': 0, 'promptInjectionSignals': 0,
                  'hasLoginIntent': True},
     'expected': 'legit'},
    {'name': 'Phish (unseen bank lookalike)',
     'url': 'https://monzo-account-alert.co/login',
     'metadata': {'title': 'Monzo - confirm your details',
                  'passwordFields': 1, 'forms': 1, 'hiddenElements': 1,
                  'externalScripts': 3, 'permissionRequests': 0,
                  'promptInjectionSignals': 1, 'hasLoginIntent': True,
                  'brandHints': 'Monzo bank security'},
     'expected': 'phish'},
]